//
// AddTimeOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** AddTimeOption options for adding time to an issue */
public struct AddTimeOption: Codable {


    /** time in seconds */
    public var time: Int64
    public init(time: Int64) { 
        self.time = time
    }

}
