//
// Branch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Branch represents a repository branch */
public struct Branch: Codable {


    public var commit: PayloadCommit?

    public var name: String?
    public init(commit: PayloadCommit?, name: String?) { 
        self.commit = commit
        self.name = name
    }

}
