//
// CreateGPGKeyOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** CreateGPGKeyOption options create user GPG key */
public struct CreateGPGKeyOption: Codable {


    /** An armored GPG key to add */
    public var armoredPublicKey: String
    public init(armoredPublicKey: String) { 
        self.armoredPublicKey = armoredPublicKey
    }
    public enum CodingKeys: String, CodingKey { 
        case armoredPublicKey = "armored_public_key"
    }

}
