//
// CreateEmailOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** CreateEmailOption options when creating email addresses */
public struct CreateEmailOption: Codable {


    /** email addresses to add */
    public var emails: [String]?
    public init(emails: [String]?) { 
        self.emails = emails
    }

}
