//
// CreateOrgOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** CreateOrgOption options for creating an organization */
public struct CreateOrgOption: Codable {


    public var _description: String?

    public var fullName: String?

    public var location: String?

    public var username: String

    public var website: String?
    public init(_description: String?, fullName: String?, location: String?, username: String, website: String?) { 
        self._description = _description
        self.fullName = fullName
        self.location = location
        self.username = username
        self.website = website
    }
    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case fullName = "full_name"
        case location
        case username
        case website
    }

}
