//
// CreateIssueCommentOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** CreateIssueCommentOption options for creating a comment on an issue */
public struct CreateIssueCommentOption: Codable {


    public var body: String
    public init(body: String) { 
        self.body = body
    }

}
