//
// DeleteEmailOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** DeleteEmailOption options when deleting email addresses */
public struct DeleteEmailOption: Codable {


    /** email addresses to delete */
    public var emails: [String]?
    public init(emails: [String]?) { 
        self.emails = emails
    }

}
