//
// EditTeamOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** EditTeamOption options for editing a team */
public struct EditTeamOption: Codable {

    public enum Permission: String, Codable { 
        case read = "read"
        case write = "write"
        case admin = "admin"
    }
    public var _description: String?

    public var name: String
    public var permission: Permission?

    public var units: [String]?
    public init(_description: String?, name: String, permission: Permission?, units: [String]?) { 
        self._description = _description
        self.name = name
        self.permission = permission
        self.units = units
    }
    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case name
        case permission
        case units
    }

}
