//
// EditAttachmentOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** EditAttachmentOptions options for editing attachments */
public struct EditAttachmentOptions: Codable {


    public var name: String?
    public init(name: String?) { 
        self.name = name
    }

}
