//
// EditIssueCommentOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** EditIssueCommentOption options for editing a comment */
public struct EditIssueCommentOption: Codable {


    public var body: String
    public init(body: String) { 
        self.body = body
    }

}
