//
// EditLabelOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** EditLabelOption options for editing a label */
public struct EditLabelOption: Codable {


    public var color: String?

    public var name: String?
    public init(color: String?, name: String?) { 
        self.color = color
        self.name = name
    }

}
