//
// EditMilestoneOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** EditMilestoneOption options for editing a milestone */
public struct EditMilestoneOption: Codable {


    public var _description: String?

    public var dueOn: Date?

    public var state: String?

    public var title: String?
    public init(_description: String?, dueOn: Date?, state: String?, title: String?) { 
        self._description = _description
        self.dueOn = dueOn
        self.state = state
        self.title = title
    }
    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case dueOn = "due_on"
        case state
        case title
    }

}
