//
// EditHookOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** EditHookOption options when modify one hook */
public struct EditHookOption: Codable {


    public var active: Bool?

    public var config: [String:String]?

    public var events: [String]?
    public init(active: Bool?, config: [String:String]?, events: [String]?) { 
        self.active = active
        self.config = config
        self.events = events
    }

}
