//
// Email.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Email an email address belonging to a user */
public struct Email: Codable {


    public var email: String?

    public var primary: Bool?

    public var verified: Bool?
    public init(email: String?, primary: Bool?, verified: Bool?) { 
        self.email = email
        self.primary = primary
        self.verified = verified
    }

}
