//
// GitEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** GitEntry represents a git tree */
public struct GitEntry: Codable {


    public var mode: String?

    public var path: String?

    public var sha: String?

    public var size: Int64?

    public var type: String?

    public var url: String?
    public init(mode: String?, path: String?, sha: String?, size: Int64?, type: String?, url: String?) { 
        self.mode = mode
        self.path = path
        self.sha = sha
        self.size = size
        self.type = type
        self.url = url
    }

}
