//
// GitObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct GitObject: Codable {


    public var sha: String?

    public var type: String?

    public var url: String?
    public init(sha: String?, type: String?, url: String?) { 
        self.sha = sha
        self.type = type
        self.url = url
    }

}
