//
// GPGKeyEmail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** GPGKeyEmail an email attached to a GPGKey */
public struct GPGKeyEmail: Codable {


    public var email: String?

    public var verified: Bool?
    public init(email: String?, verified: Bool?) { 
        self.email = email
        self.verified = verified
    }

}
