//
// IssueDeadline.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** IssueDeadline represents an issue deadline */
public struct IssueDeadline: Codable {


    public var dueDate: Date?
    public init(dueDate: Date?) { 
        self.dueDate = dueDate
    }
    public enum CodingKeys: String, CodingKey { 
        case dueDate = "due_date"
    }

}
