//
// IssueLabelsOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** IssueLabelsOption a collection of labels */
public struct IssueLabelsOption: Codable {


    /** list of label IDs */
    public var labels: [Int64]?
    public init(labels: [Int64]?) { 
        self.labels = labels
    }

}
