//
// MergePullRequestOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** MergePullRequestForm form for merging Pull Request */
public struct MergePullRequestOption: Codable {

    public enum Do: String, Codable { 
        case merge = "merge"
        case rebase = "rebase"
        case rebaseMerge = "rebase-merge"
        case squash = "squash"
    }
    
    public var _do: Do

    public var mergeMessageField: String?

    public var mergeTitleField: String?
    public init(_do: Do, mergeMessageField: String?, mergeTitleField: String?) { 
        self._do = _do
        self.mergeMessageField = mergeMessageField
        self.mergeTitleField = mergeTitleField
    }
    public enum CodingKeys: String, CodingKey { 
        case _do = "Do"
        case mergeMessageField = "MergeMessageField"
        case mergeTitleField = "MergeTitleField"
    }

}
