//
// PayloadUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** PayloadUser represents the author or committer of a commit */
public struct PayloadUser: Codable {


    public var email: String?

    /** Full name of the commit author */
    public var name: String?

    public var username: String?
    public init(email: String?, name: String?, username: String?) { 
        self.email = email
        self.name = name
        self.username = username
    }

}
