//
// Permission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Permission represents a set of permissions */
public struct Permission: Codable {


    public var admin: Bool?

    public var pull: Bool?

    public var push: Bool?
    public init(admin: Bool?, pull: Bool?, push: Bool?) { 
        self.admin = admin
        self.pull = pull
        self.push = push
    }

}
