//
// PRBranchInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** PRBranchInfo information about a branch */
public struct PRBranchInfo: Codable {


    public var label: String?

    public var ref: String?

    public var repo: Repository?

    public var repoId: Int64?

    public var sha: String?
    public init(label: String?, ref: String?, repo: Repository?, repoId: Int64?, sha: String?) { 
        self.label = label
        self.ref = ref
        self.repo = repo
        self.repoId = repoId
        self.sha = sha
    }
    public enum CodingKeys: String, CodingKey { 
        case label
        case ref
        case repo
        case repoId = "repo_id"
        case sha
    }

}
