//
// RepoCommit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct RepoCommit: Codable {


    public var author: CommitUser?

    public var committer: CommitUser?

    public var message: String?

    public var tree: CommitMeta?

    public var url: String?
    public init(author: CommitUser?, committer: CommitUser?, message: String?, tree: CommitMeta?, url: String?) { 
        self.author = author
        self.committer = committer
        self.message = message
        self.tree = tree
        self.url = url
    }

}
