//
// SearchResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** SearchResults results of a successful search */
public struct SearchResults: Codable {


    public var data: [Repository]?

    public var ok: Bool?
    public init(data: [Repository]?, ok: Bool?) { 
        self.data = data
        self.ok = ok
    }

}
