//
// ServerVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** ServerVersion wraps the version of the server */
public struct ServerVersion: Codable {


    public var version: String?
    public init(version: String?) { 
        self.version = version
    }

}
