//
// StateType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** StateType issue state type */
public struct StateType: Codable {


}
