//
// TimeStamp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** TimeStamp defines a timestamp */
public struct TimeStamp: Codable {


}
