//
// UserHeatmapData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** UserHeatmapData represents the data needed to create a heatmap */
public struct UserHeatmapData: Codable {


    public var contributions: Int64?

    public var timestamp: TimeStamp?
    public init(contributions: Int64?, timestamp: TimeStamp?) { 
        self.contributions = contributions
        self.timestamp = timestamp
    }

}
