//
// WatchInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** WatchInfo represents an API watch status of one repository */
public struct WatchInfo: Codable {


    public var createdAt: Date?

    public var ignored: Bool?

    public var repositoryUrl: String?

    public var subscribed: Bool?

    public var url: String?
    public init(createdAt: Date?, ignored: Bool?, repositoryUrl: String?, subscribed: Bool?, url: String?) {
        self.createdAt = createdAt
        self.ignored = ignored
        self.repositoryUrl = repositoryUrl
        self.subscribed = subscribed
        self.url = url
    }
    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case ignored
        case repositoryUrl = "repository_url"
        case subscribed
        case url
    }

}
